name: Docker Image CI

on:
  push:
    branches: [ "release" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: "adopt"
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: "sud0x67"
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file ./Dockerfile --tag sud0x67/crypto-trade:latest
    - name: Push to private dockerhub
      run: docker push sud0x67/crypto-trade:latest
